---
kind: pipeline
type: docker
name: Building..
node:
  drone: ch1
steps:
  - name: build & push php8
    image: plugins/docker
    settings:
      repo: ch1ch1/nginx-http3
      tags: [ "1.16.1" ]
      username: ch1ch1
      password:
        from_secret: dockerhub_token
  - name: notification
    image: plugins/webhook
    settings:
      urls:
        from_secret: webhookgotify
      content_type: application/json
      template: |
        {
         "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
         "priority": 4,
         "title": "{{ repo.name }} build"
        }
    when:
      status: [success, failure]

trigger:
  event:
    - push
---
kind: signature
hmac: a7bbc964be8e70f17bf07a42f4b909911d800aac6b70b010573f498db6228d80

...
